# Generated by Django 4.0.2 on 2022-02-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='reciperequirement',
            old_name='ingrediente',
            new_name='ingredient',
        ),
    ]
